In [1]:
import pandas as pd

chunks = []
chunk_size = 500_000
sample_fraction = 0.02

for chunk in pd.read_csv("data/recommendations.csv",chunksize=chunk_size):
    sampled = chunk.sample(frac=sample_fraction,random_state=0)
    chunks.append(sampled)

recommendations_df = pd.concat(chunks,ignore_index=True)
print(len(recommendations_df))

823096

In [2]:
chunks = []
chunk_size = 500_000
sample_fraction = 0.025

for chunk in pd.read_csv("data/users.csv",chunksize=chunk_size):
    sampled = chunk.sample(frac=sample_fraction,random_state=0)
    chunks.append(sampled)
    
users_df = pd.concat(chunks,ignore_index=True)
print(len(users_df))

357652

In [3]:
games_df = pd.read_csv("data/games.csv")
print(len(games_df))

50872

In [6]:
import sqlite3

connection = sqlite3.connect("steam.db")
connection.execute("DROP TABLE IF EXISTS recommendations")
connection.execute("DROP TABLE IF EXISTS users")
connection.execute("DROP TABLE IF EXISTS games")
connection.commit()

In [7]:
recommendations_df.to_sql("Recommendations",connection,if_exists="replace",index=False)
users_df.to_sql("Users",connection,if_exists="replace",index=False)
games_df.to_sql("Games",connection,if_exists="replace",index=False)

50872

In [8]:
import os
print(f"{os.path.getsize('steam.db') / (1024*1024):.1f} MB")

42.7 MB

In [13]:
pd.read_sql_query("select * from Recommendations limit 15;",connection)

,app_id,helpful,funny,date,is_recommended,hours,user_id,review_id
0,1172620,0,0,2021-07-07,1,13.2,13135506,194257
1,1229490,0,0,2021-08-03,1,43.3,939580,396319
2,489830,12,0,2018-09-17,0,385.4,13990925,138738
3,275850,5,0,2016-08-14,1,130.6,84455,66570
4,730,2,0,2016-03-03,1,550.0,7870783,149424
5,632360,0,0,2022-01-12,1,125.3,13373786,128165
6,107410,5,0,2017-08-17,1,704.9,8226463,264495
7,1817070,0,0,2022-08-16,1,30.6,912530,30371
8,108600,0,0,2022-12-11,1,573.4,2982774,456998
9,270880,0,0,2020-04-09,1,416.4,9779722,32001
10,271590,0,0,2016-01-17,0,300.7,5019313,451744
11,252490,0,0,2021-08-13,1,237.1,11755009,177149
12,291550,0,0,2022-07-09,1,6.2,3775322,137464
13,292030,0,3,2016-06-11,1,11.9,11405697,103416
14,202970,0,3,2016-04-27,1,0.3,7423228,156487

In [12]:
pd.read_sql_query("select * from Users limit 15;",connection)

     user_id  products  reviews
0   13107398        19        1
1    8854310        44        1
2    3204231        19        0
3    2971603        19        3
4   11478991        45        1
5     363627        57        0
6   12808426         8        5
7    7036514       287       22
8    6293407        62        1
9    7393956        14        1
10   5178394        50        1
11   7928965        28        1
12   2833486        62        1
13   7402308        53        9
14    794968        71        1

In [14]:
pd.read_sql_query("select * from Games limit 15;",connection)

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,13500,Prince of Persia: Warrior Within™,2008-11-21,1,0,0,Very Positive,84,2199,9.99,9.99,0.0,1
1,22364,BRINK: Agents of Change,2011-08-03,1,0,0,Positive,85,21,2.99,2.99,0.0,1
2,113020,Monaco: What's Yours Is Mine,2013-04-24,1,1,1,Very Positive,92,3722,14.99,14.99,0.0,1
3,226560,Escape Dead Island,2014-11-18,1,0,0,Mixed,61,873,14.99,14.99,0.0,1
4,249050,Dungeon of the ENDLESS™,2014-10-27,1,1,0,Very Positive,88,8784,11.99,11.99,0.0,1
5,250180,METAL SLUG 3,2015-09-14,1,0,0,Very Positive,90,5579,7.99,7.99,0.0,1
6,253980,Enclave,2013-10-04,1,1,1,Mostly Positive,75,1608,4.99,4.99,0.0,1
7,271850,Men of War: Assault Squad 2 - Deluxe Edition u...,2014-05-16,1,0,0,Mixed,61,199,6.99,6.99,0.0,1
8,282900,Hyperdimension Neptunia Re;Birth1,2015-01-29,1,0,0,Very Positive,94,9686,14.99,14.99,0.0,1
9,19810,The Sum of All Fears,2008-10-10,1,0,0,Mostly Positive,75,33,9.99,9.99,0.0,1
10,15270,Cold Fear™,2008-05-13,1,0,0,Very Positive,85,800,9.99,9.99,0.0,1
11,21130,LEGO® Harry Potter: Years 1-4,2010-06-25,1,0,0,Very Positive,85,5169,19.99,19.99,0.0,1
12,22130,Hearts of Iron 2 Complete,2009-01-23,1,0,0,Very Positive,85,462,14.99,14.99,0.0,1
13,29180,Osmos,2009-08-18,1,1,1,Very Positive,88,532,9.99,9.99,0.0,1
14,32750,Comanche 4,2009-06-18,1,0,0,Very Positive,90,222,9.99,9.99,0.0,1